### PR TITLE
Configure logging initialization such that it can be readily initiali…

### LINKED ISSUE #540: Allow programmatic execution without importing aspen.__main__
Logging should be implicitly configured or available to be explicitly configured, per [this comment](https://github.com/gratipay/aspen.py/commit/a1df2bae9293d2f1f40e05a17d7de699638e18c0#commitcomment-15565648).

### PR DESCRIPTION
**Pull request by jaraco**
…zed by a programmatic execution of aspen. Fixes #540.

Feel free to reject and develop an alternative, accept and tweak, or accept as-is.

### CODE REVIEW

**Comment by whit537** [comment]
Picking up from #540 ...

> Okay, upon looking at this again, the current code is correct because: `init_logging` initializes handlers and formats and such, which _a module should NOT do_.  This is why it's done in `__main__`.  

@pjz The way I read this PR, `init_logging` initializes handlers, yes, and it's *defined* in `__init__` ... but it's not *called* except during `python -m aspen` via `__main__` (notice the `functools.partial` at https://github.com/jaraco/aspen/blob/6c920a68ac7912188e23ca19a743edba22a540ff/aspen/__init__.py#L104). No?

**Comment by whit537** [comment]
In other words, I think @pjz's concerns are misplaced, and I'm :+1: here.

Am I missing something, @pjz?

**Comment by jaraco** [comment]
That's the intention - expose the functionality so another caller might be able to re-use it, but still call it by default only in `__main__`.

**Comment by pjz** [comment]
Looking at the `__main__` code now, I think that `serve()` should NOT have been refactored into `__init__.py` for similar reasons as I think `init_logging()` shouldn't be:  The goal of `python -m aspen` is to serve as 1: a test/dev toy server and also 2: example code.  Literally nothing else ever in the aspen module will call or use `serve()` and `init_logging()`.  Production deploys shouldn't use them either - they should use uwsgi or the like to call a minimal wrapper around the WSGI entry point.  I much prefer to not add an extra support/documentation burden to the module by instead encouraging people to copy the `__main__` as a starting point.

**Comment by pjz** [comment]
I'd prefer the solution embodied by #545.

**Comment by whit537** [comment]
Closing per https://github.com/gratipay/aspen.py/issues/540#issuecomment-176803859.

**Pull request closed without merging**
