### PR TITLE
replace backcompat with six

### PR DESCRIPTION
**Pull request by whit537**

### CODE REVIEW

**Comment by pjz** [comment]
Should this go in before anything's using it?  Or if it's intended to replace backcompat, backcompat should be removed and everything that uses it switched over to using six ?

**Comment by whit537** [comment]
@pjz I would leave this PR open until we're actually ported. 6265e1e506318182832807c84e59b707819b006d is just the first commit. Next step imo would be to migrate our `backcompat` usage to `six` and remove `backcompat`. We could merge at that point if we don't have momentum to finish porting.

**Comment by pjz** [comment]
...then this shouldn't be a PR, it should just be a branch. PR means 'ready to be reviewed and then merged'.

**Comment by whit537** [comment]
> PR means 'ready to be reviewed and then merged'.

Not necessarily. That's what the `Review` label is for. ;-)

Starting a PR early is valuable because it gives us a place to discuss implementation details as they arise, and in general it makes it easier for multiple people to collaborate on one piece of work.

**Comment by whit537** [comment]
Title changed to reflect limited scope.

**Comment by whit537** [comment]
I've whittled it down. It's not obvious to me that `six` supports that last two transformations (`md5` and `html_escape`). I propose that we merge this PR as it stands now and reticket those two items.

**Comment by whit537** [comment]
Ping @pjz.

**Comment by pjz** [comment]
Why are we shipping a copy of six instead of depending on it?  Won't this open us up to having to keep updating to keep up with bugfixes?  What's the best practices with this?

**Comment by whit537** [comment]
> What's the best practices with this?

Dunno. They [advertise](https://pypi.python.org/pypi/six) that "[Six] is contained in only one Python file, so it can be easily copied into your project." I took from that that that's how it was designed to be used.

**Comment by whit537** [comment]
> Won't this open us up to having to keep updating to keep up with bugfixes?

Yes. We will have to download the new version of the file instead of updating the line in `requirements.txt`.

**Comment by pjz** [comment]
Let's depend on it instead of including it.

**Comment by Changaco** [comment]
I usually find it cleaner to write the compatibility code for the few things needed than to use `six`.

**Comment by pjz** [comment]
We tried that, six is nicer.  Also, six is likely to be more forward compatible with, say, py3.{5,6,...}

**Comment by whit537** [comment]
@Changaco That's what I've done on other projects. Figured I'd give six a try here. It's not so bad so far, though as mentioned it appears to have some holes.

**Comment by whit537** [comment]
> Let's depend on it instead of including it.

What version range should we target? For reference, here's our current dependencies [in `setup.py`](https://github.com/gratipay/aspen.py/blob/0.42/setup.py#L37-L41):

```python
 37      , install_requires = [ 'python-mimeparse==0.1.4'                                                     
 38                           , 'first==2.0.1'                                                                
 39                           , 'algorithm>=1.0.0'                                                            
 40                           , 'filesystem_tree>=1.0.0'                                                      
 41                            ] 
```

Since we pin exact versions of `python-mimeparse` and `first`, we are already running the risk of dependency hell (I want to use Aspen, but I also want to use PyFoo, which depends on `first > 2.0.1`). We increase that risk *greatly* if we pin `six`, because it's the `*ahem*` [sixth-most popular package on PyPI](http://pypi-ranking.info/alltime).

However, if we use ranges, as with `algorithm` and `filesystem_tree`, we run the risk of API drift (despite any given project's best efforts at semantic versioning). We will end up coding around changes in `six`: we'll need a backcompat layer for our backcompat layer.

**Comment by pjz** [comment]
I'd say use a range and run the risk of API drift; if it happens it happens, we'll deal with it when it does.

**Comment by whit537** [comment]
Abandoning. We'll revisit #524 after #527.

**Pull request closed without merging**
