### PR TITLE
fold configuration into processor

### PR DESCRIPTION
**Pull request by whit537**
The processor is so thin now, there's no sense having a separate mixin for configuration.

### CODE REVIEW

**Comment by whit537** [comment]
Ping @pjz @Changaco.

**Comment by pjz** [comment]
In general, 'processor' is a terrible name.  Processor of what?

**Comment by pjz** [comment]
Since the configuration is via code now, can't we ditch most of `processor/parse.p`y and roll the rest into `processor/__init__.py` and then turn that back into `processor.py`?

**Comment by whit537** [comment]
> In general, 'processor' is a terrible name. Processor of what?

Fair enough. What would you suggest instead?

As I work on this, it strikes me that Aspen is still a web framework, albeit a parasitic one. There's no reason we can't write a `wsgiref` shim to go along with shims for `flask` and `django`, so that `python -m aspen` still works out of the box. Which is to say that the "processor" is a processor of web requests.

My current thinking is that we should have a package layout with four main parts. In order of increasing dependency, they are:

 1. **`aspen.utils`**—Includes `backcompat` and `testing`.
 1. **`aspen.simplates`**—Defines the `Simplate` class, and includes subpackages for renderers, pagination, and json handling.
 1. **`aspen.http`**—Defines classes that model the parts of HTTP that we still need in order to do our work, which is significantly constrained relative to Aspen 0.42. It uses `aspen.simplates` to model dynamic resources.
 1. **`aspen.processor`**—Uses the classes defined in `aspen.http` to respond to concrete web requests within the context of a host web framework. Includes dispatch, typecasting, and algorithms ("state chains," in the [new parlance](https://github.com/gratipay/algorithm.py/issues/3)).

Proposed:

```
aspen
├── __init__.py
├── __main__.py
├── http
│   ├── __init__.py
│   ├── mapping.py
│   ├── request.py
│   └── resource
│       ├── __init__.py
│       ├── dynamic.py
│       └── static.py
├── processor
│   ├── __init__.py
│   ├── base
│   │   ├── algorithm.py
│   │   ├── dispatcher.py
│   │   ├── mime.types
│   │   ├── parse.py
│   │   └── typecasting.py
│   ├── django.py
│   ├── flask.py
│   └── wsgiref.py
├── simplates
│   ├── __init__.py
│   ├── json_.py
│   ├── pagination.py
│   ├── renderers
│   │   ├── __init__.py
│   │   ├── json_dump.py
│   │   ├── jsonp_dump.py
│   │   ├── stdlib_format.py
│   │   ├── stdlib_percent.py
│   │   └── stdlib_template.py
│   └── simplate.py
└── utils
    ├── __init__.py
    ├── backcompat.py
    └── testing.py
```

Current `just-simplates`:

```
aspen
├── __init__.py
├── algorithm.py
├── backcompat.py
├── configuration
│   ├── __init__.py
│   ├── mime.types
│   └── parse.py
├── dispatcher.py
├── exceptions.py
├── http
│   ├── __init__.py
│   ├── mapping.py
│   ├── request.py
│   └── resource.py
├── json_.py
├── output.py
├── pagination.py
├── processor.py
├── renderers
│   ├── __init__.py
│   ├── json_dump.py
│   ├── jsonp_dump.py
│   ├── stdlib_format.py
│   ├── stdlib_percent.py
│   └── stdlib_template.py
├── resources.py
├── simplates.py
├── testing.py
├── typecasting.py
└── utils.py
```

Current `master`:

```
aspen
├── __init__.py
├── __main__.py
├── algorithms
│   ├── __init__.py
│   └── website.py
├── auth
│   ├── __init__.py
│   ├── cookie.py
│   ├── httpbasic.py
│   └── httpdigest.py
├── backcompat.py
├── body_parsers.py
├── configuration
│   ├── __init__.py
│   ├── mime.types
│   └── parse.py
├── dispatcher.py
├── exceptions.py
├── http
│   ├── __init__.py
│   ├── baseheaders.py
│   ├── mapping.py
│   ├── request.py
│   ├── resource.py
│   └── response.py
├── json_.py
├── logging.py
├── renderers.py
├── resources.py
├── simplates
│   ├── __init__.py
│   ├── pagination.py
│   └── renderers
│       ├── __init__.py
│       ├── json_dump.py
│       ├── jsonp_dump.py
│       ├── stdlib_format.py
│       ├── stdlib_percent.py
│       └── stdlib_template.py
├── testing
│   ├── __init__.py
│   ├── client.py
│   ├── harness.py
│   └── pytest_fixtures.py
├── typecasting.py
├── utils.py
├── website.py
├── wsgi.py
└── www
    ├── autoindex.html.spt
    ├── error.spt
    └── favicon.ico
```

**Comment by pjz** [comment]
'RequestHandler' maybe?  That's descriptive, righ

**Comment by pjz** [comment]
Also, the proposal looks to have too many layers: 3 most places instead of the existing 2.

**Comment by whit537** [comment]
@pjz How about this?

 - move host-framework-specific code to `aspen.shims` (we may move these to separate packages eventually anyway)
 - flatten `aspen.processor.base` to `aspen.request_processor`
 - if/when we factor out `simplates` we would lose a three-level nesting

```
aspen
├── __init__.py
├── __main__.py
├── http
│   ├── __init__.py
│   ├── mapping.py
│   ├── request.py
│   └── resource
│       ├── __init__.py
│       ├── dynamic.py
│       └── static.py
├── request_processor
│   ├── __init__.py
│   ├── algorithm.py
│   ├── dispatcher.py
│   ├── mime.types
│   ├── parse.py
│   └── typecasting.py
├── shims
│   ├── __init__.py
│   ├── django.py
│   ├── flask.py
│   └── wsgiref.py
├── simplates
│   ├── __init__.py
│   ├── json_.py
│   ├── pagination.py
│   ├── renderers
│   │   ├── __init__.py
│   │   ├── json_dump.py
│   │   ├── jsonp_dump.py
│   │   ├── stdlib_format.py
│   │   ├── stdlib_percent.py
│   │   └── stdlib_template.py
│   └── simplate.py
└── utils
    ├── __init__.py
    ├── backcompat.py
    └── testing.py
```

**Comment by pjz** [comment]
That looks better, but...  is the top level `aspen` empty then?  And what's in `utils.__init` ?  And  what's actually left in `http`?  I thought the point of this was to not have that.. It should be subsumed by the shims, no?

**Comment by whit537** [comment]
> is the top level aspen empty then?

Empty of what? It has an `__init__.py`, a `__main__.py`, and four submodules.

> And what's in utils.__init ?

The current contents of `utils.py`, maybe minus `to_age` and whatever else we can jettison.

> And what's actually left in `http`?

The [current contents of `http` on `just-simplates`](https://github.com/gratipay/aspen.py/tree/1ce9aa2c7dec2f0179a4fccf4bfff2269e3b2ec9/aspen/http), plus the current `resources.py` moved to `resources/__init__.py` and the current `http/resource.py` moved under `resources/` as well.

> I thought the point of this was to not have that.. It should be subsumed by the shims, no?

It's true that we no longer have full-blown request and response objects; we now depend on the shims for those. However, over on #527, we're currently still using the `Path` class for dispatch, along with `PathParts` and `Querystring`. Do you think we should try harder to get rid of those?

**Comment by whit537** [comment]
d757bb218351741d5d35300e6139e4793be86140 look better?

**Pull request merged**
