### PR TITLE
Added no-op functions to website algorithm for easy hookage

### LINKED ISSUE #424: add high-level noop functions to algorithm
Algorithm.py supports [two modification strategies](http://algorithm-py.readthedocs.org/en/latest/#modifying-an-algorithm), a simple one using `insert_before,after` and `remove` methods, and a complex one using `.functions` assignment. For the simple case we should add three noop functions that signal the availability of our main objects: request, resource, and response.

We could talk about an exception hook as well.

### PR DESCRIPTION
**Pull request by pjz**
Fix #424

### CODE REVIEW

**Comment by whit537** [comment]
I'll let you get away without further doc besides the docstring, but we should have a test or two for these.

**Comment by pjz** [comment]
tests? for no-op functions?  They exist solely for `algorithm.py` to put names on them.  What would such a test look like?  And would it really be testing aspen functionality, or `algorithm.py` functionality?

**Comment by Changaco** [comment]
Reminder: function calls are not free, they cost CPU cycles even if they do nothing. The more functions there are in the algorithm the slower it is, even if it may not be noticeable.

**Comment by pjz** [comment]
Fair point, but my understanding of `algorithm.py` is that they *have* to be empty functions: if we just do like `request_available = parse_body_into_request` then `parse_body_into_request` will be called *twice*, which is not what we want.

**Comment by Changaco** [comment]
Hooks that have no run-time cost could be implemented in algorithm.py, but this PR doesn't need to be blocked on that.

**Comment by whit537** [comment]
Remember, too, that projects using Aspen are encouraged to define their own algorithm. You don't have to include these noop functions if you don't want to.

**Comment by pjz** [comment]
so... mergable?

**Pull request merged**
